# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.12

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

# Include any dependencies generated for this target.
include src\CMakeFiles\common_obj.dir\depend.make

# Include the progress variables for this target.
include src\CMakeFiles\common_obj.dir\progress.make

# Include the compile flags for this target's objects.
include src\CMakeFiles\common_obj.dir\flags.make

src\CMakeFiles\common_obj.dir\MQTTTime.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTTime.c.obj: ..\src\MQTTTime.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/CMakeFiles/common_obj.dir/MQTTTime.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTTime.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTTime.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTTime.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTTime.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTTime.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTTime.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTTime.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTTime.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTTime.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTTime.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProtocolClient.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTProtocolClient.c.obj: ..\src\MQTTProtocolClient.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolClient.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTProtocolClient.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProtocolClient.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProtocolClient.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTProtocolClient.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTProtocolClient.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProtocolClient.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProtocolClient.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTProtocolClient.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTProtocolClient.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProtocolClient.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Clients.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Clients.c.obj: ..\src\Clients.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object src/CMakeFiles/common_obj.dir/Clients.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Clients.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Clients.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Clients.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Clients.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Clients.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Clients.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Clients.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Clients.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Clients.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Clients.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\utf-8.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\utf-8.c.obj: ..\src\utf-8.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object src/CMakeFiles/common_obj.dir/utf-8.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\utf-8.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\utf-8.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\utf-8.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/utf-8.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\utf-8.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\utf-8.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\utf-8.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/utf-8.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\utf-8.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\utf-8.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPacket.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTPacket.c.obj: ..\src\MQTTPacket.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object src/CMakeFiles/common_obj.dir/MQTTPacket.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTPacket.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPacket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPacket.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTPacket.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTPacket.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPacket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPacket.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTPacket.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTPacket.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPacket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPacketOut.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTPacketOut.c.obj: ..\src\MQTTPacketOut.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object src/CMakeFiles/common_obj.dir/MQTTPacketOut.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTPacketOut.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPacketOut.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPacketOut.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTPacketOut.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTPacketOut.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPacketOut.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPacketOut.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTPacketOut.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTPacketOut.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPacketOut.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Messages.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Messages.c.obj: ..\src\Messages.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object src/CMakeFiles/common_obj.dir/Messages.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Messages.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Messages.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Messages.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Messages.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Messages.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Messages.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Messages.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Messages.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Messages.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Messages.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Tree.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Tree.c.obj: ..\src\Tree.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object src/CMakeFiles/common_obj.dir/Tree.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Tree.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Tree.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Tree.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Tree.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Tree.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Tree.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Tree.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Tree.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Tree.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Tree.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Socket.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Socket.c.obj: ..\src\Socket.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object src/CMakeFiles/common_obj.dir/Socket.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Socket.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Socket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Socket.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Socket.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Socket.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Socket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Socket.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Socket.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Socket.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Socket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Log.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Log.c.obj: ..\src\Log.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object src/CMakeFiles/common_obj.dir/Log.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Log.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Log.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Log.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Log.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Log.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Log.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Log.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Log.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Log.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Log.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPersistence.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTPersistence.c.obj: ..\src\MQTTPersistence.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object src/CMakeFiles/common_obj.dir/MQTTPersistence.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTPersistence.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPersistence.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPersistence.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTPersistence.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTPersistence.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPersistence.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPersistence.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTPersistence.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTPersistence.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPersistence.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Thread.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Thread.c.obj: ..\src\Thread.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building C object src/CMakeFiles/common_obj.dir/Thread.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Thread.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Thread.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Thread.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Thread.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Thread.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Thread.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Thread.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Thread.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Thread.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Thread.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProtocolOut.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTProtocolOut.c.obj: ..\src\MQTTProtocolOut.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolOut.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTProtocolOut.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProtocolOut.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProtocolOut.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTProtocolOut.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTProtocolOut.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProtocolOut.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProtocolOut.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTProtocolOut.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTProtocolOut.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProtocolOut.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.obj: ..\src\MQTTPersistenceDefault.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building C object src/CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPersistenceDefault.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPersistenceDefault.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTPersistenceDefault.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\SocketBuffer.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\SocketBuffer.c.obj: ..\src\SocketBuffer.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building C object src/CMakeFiles/common_obj.dir/SocketBuffer.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\SocketBuffer.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\SocketBuffer.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\SocketBuffer.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/SocketBuffer.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\SocketBuffer.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\SocketBuffer.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\SocketBuffer.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/SocketBuffer.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\SocketBuffer.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\SocketBuffer.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\LinkedList.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\LinkedList.c.obj: ..\src\LinkedList.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building C object src/CMakeFiles/common_obj.dir/LinkedList.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\LinkedList.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\LinkedList.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\LinkedList.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/LinkedList.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\LinkedList.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\LinkedList.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\LinkedList.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/LinkedList.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\LinkedList.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\LinkedList.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProperties.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTProperties.c.obj: ..\src\MQTTProperties.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Building C object src/CMakeFiles/common_obj.dir/MQTTProperties.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTProperties.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProperties.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProperties.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTProperties.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTProperties.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProperties.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTProperties.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTProperties.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTProperties.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTProperties.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTReasonCodes.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\MQTTReasonCodes.c.obj: ..\src\MQTTReasonCodes.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_18) "Building C object src/CMakeFiles/common_obj.dir/MQTTReasonCodes.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\MQTTReasonCodes.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTReasonCodes.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTReasonCodes.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/MQTTReasonCodes.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\MQTTReasonCodes.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTReasonCodes.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\MQTTReasonCodes.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/MQTTReasonCodes.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\MQTTReasonCodes.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\MQTTReasonCodes.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Base64.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Base64.c.obj: ..\src\Base64.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_19) "Building C object src/CMakeFiles/common_obj.dir/Base64.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Base64.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Base64.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Base64.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Base64.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Base64.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Base64.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Base64.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Base64.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Base64.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Base64.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\SHA1.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\SHA1.c.obj: ..\src\SHA1.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_20) "Building C object src/CMakeFiles/common_obj.dir/SHA1.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\SHA1.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\SHA1.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\SHA1.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/SHA1.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\SHA1.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\SHA1.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\SHA1.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/SHA1.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\SHA1.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\SHA1.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\WebSocket.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\WebSocket.c.obj: ..\src\WebSocket.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_21) "Building C object src/CMakeFiles/common_obj.dir/WebSocket.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\WebSocket.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\WebSocket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\WebSocket.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/WebSocket.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\WebSocket.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\WebSocket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\WebSocket.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/WebSocket.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\WebSocket.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\WebSocket.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\StackTrace.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\StackTrace.c.obj: ..\src\StackTrace.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_22) "Building C object src/CMakeFiles/common_obj.dir/StackTrace.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\StackTrace.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\StackTrace.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\StackTrace.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/StackTrace.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\StackTrace.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\StackTrace.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\StackTrace.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/StackTrace.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\StackTrace.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\StackTrace.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Heap.c.obj: src\CMakeFiles\common_obj.dir\flags.make
src\CMakeFiles\common_obj.dir\Heap.c.obj: ..\src\Heap.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\CMakeFiles --progress-num=$(CMAKE_PROGRESS_23) "Building C object src/CMakeFiles/common_obj.dir/Heap.c.obj"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoCMakeFiles\common_obj.dir\Heap.c.obj /FdCMakeFiles\common_obj.dir\ /FS -c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Heap.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Heap.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/common_obj.dir/Heap.c.i"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe > CMakeFiles\common_obj.dir\Heap.c.i @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Heap.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

src\CMakeFiles\common_obj.dir\Heap.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/common_obj.dir/Heap.c.s"
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe @<<
  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) /FoNUL /FAs /FaCMakeFiles\common_obj.dir\Heap.c.s /c C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src\Heap.c
<<
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho

common_obj: src\CMakeFiles\common_obj.dir\MQTTTime.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTProtocolClient.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Clients.c.obj
common_obj: src\CMakeFiles\common_obj.dir\utf-8.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTPacket.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTPacketOut.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Messages.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Tree.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Socket.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Log.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTPersistence.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Thread.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTProtocolOut.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTPersistenceDefault.c.obj
common_obj: src\CMakeFiles\common_obj.dir\SocketBuffer.c.obj
common_obj: src\CMakeFiles\common_obj.dir\LinkedList.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTProperties.c.obj
common_obj: src\CMakeFiles\common_obj.dir\MQTTReasonCodes.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Base64.c.obj
common_obj: src\CMakeFiles\common_obj.dir\SHA1.c.obj
common_obj: src\CMakeFiles\common_obj.dir\WebSocket.c.obj
common_obj: src\CMakeFiles\common_obj.dir\StackTrace.c.obj
common_obj: src\CMakeFiles\common_obj.dir\Heap.c.obj
common_obj: src\CMakeFiles\common_obj.dir\build.make

.PHONY : common_obj

# Rule to build all files generated by this target.
src\CMakeFiles\common_obj.dir\build: common_obj

.PHONY : src\CMakeFiles\common_obj.dir\build

src\CMakeFiles\common_obj.dir\clean:
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src
	$(CMAKE_COMMAND) -P CMakeFiles\common_obj.dir\cmake_clean.cmake
	cd C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho
.PHONY : src\CMakeFiles\common_obj.dir\clean

src\CMakeFiles\common_obj.dir\depend:
	$(CMAKE_COMMAND) -E cmake_depends "NMake Makefiles" C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\src C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src C:\Users\ASUS\Documents\GitHub\paho.mqtt.c-master\build.paho\src\CMakeFiles\common_obj.dir\DependInfo.cmake --color=$(COLOR)
.PHONY : src\CMakeFiles\common_obj.dir\depend

