# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.12

# compile C with C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
C_FLAGS = /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG   -MD

C_DEFINES = -DPAHO_MQTT_EXPORTS=1 -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE

C_INCLUDES = 

